def raiseError():
    raise ValueError("Error")
